# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application
# Event 언제 Workflow가 실행될 것인가?
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# jobs 정의, build는 job의 이름!
jobs:
  build:

    runs-on: ubuntu-latest # ubuntu 환경에서 실행될 것이다. / OS환경을 의미함
    # uses : 사용할 github Action 
    # name : Step의 이름을 말한다.
    # uses가 없는 경우( ex) Install dependencises) 직접 run에 shell script 작성 후 실행
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run hello World
      run: |
        python hello-world.py 
